package:
  create:
    max_package_size: "1000000000"
    set:
      # renovate: datasource=gitlab-tags depName=big-bang/bigbang versioning=semver registryUrl=https://repo1.dso.mil
      bigbang_version: "2.7.1"
      # should line up with the flux version in the BB release, see https://repo1.dso.mil/big-bang/bigbang/-/blob/master/base/flux/gotk-components.yaml#L3
      flux_version: "2.0.1"
      terraform_version: "1.4.2"
      terraform_provider_aws_version: 4.59.0
  deploy:
    set:
      # -- Name of the EKS cluster
      name: "mnagel-dev"
      # -- AWS region
      region: us-west-1
      # -- Provision a private/internal load balancer for the admin ingress gateway, if false a public load balancer will be provisioned
      private_admin_lb: true
      # -- Provision a private/internal load balancer for the tenant ingress gateway, if false a public load balancer will be provisioned
      private_tenant_lb: true
      # -- If set to true, force delete all resources on removal (i.e. loki S3 bucket, PVCs, etc)
      ephemeral: true
      # -- Bring your own kms key, if omitted a key will be created with an alias prefix of "<cluster name>-loki-"
      #loki_kms_key_arn: "arn:aws:kms:us-west-2:000000000000:key/mrk-0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a"
      # -- Bring your own kms key, if omitted a key will be created with an alias prefix of "<cluster name>-velero-"
      #velero_kms_key_arn: "arn:aws:kms:us-west-2:000000000000:key/mrk-0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a"
